### ISSUE TITLE
Logging does not work

### ISSUE THREAD

**Issue by tiago-cruz-movile** [Banno/getsentry-ldap-auth#1]
Hello,

I'm using sentry (7.6.2) and sentry-ldap-auth (1.0), with:

```
[root@charlotte1 ~]# /sentry/env/bin/pip list | grep django
django-auth-ldap (1.2.7)
django-bitfield (1.7.1)
django-crispy-forms (1.4.0)
django-jsonfield (0.9.13)
django-paging (0.2.5)
django-picklefield (0.3.1)
django-recaptcha (1.0.4)
django-social-auth (0.7.28)
django-statsd-mozilla (0.3.14)
django-sudo (1.1.3)
django-templatetag-sugar (1.0)
djangorestframework (2.3.14)
pytest-django (2.8.0)
```

Also, I'm using in /etc/sentry/sentry.conf.py:

```
import logging
logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
logger.setLevel('DEBUG')
```

But there is any logging generetady by the supervisord about the login

```
[root@charlotte1 ~]# egrep '\[|log' /etc/supervisord.d/sentry.ini
[program:sentry-web]
stdout_logfile=/logs/sentry/sentry-web.log
stderr_logfile=/logs/sentry/sentry-web-err.log
[program:sentry-worker]
stdout_logfile=/logs/sentry/sentry-worker.log
stderr_logfile=/logs/sentry/sentry-worker-err.log
```

There is something missing?

Thanks!

**Comment by ChadKillingsworth** [comment]
I haven't tested this, but the logging might be based on the overridden name. Have you tried:

```
logger = logging.getLogger('sentry-ldap-auth')
```

**Comment by tiago-cruz-movile** [comment]
Hello @ChadKillingsworth,

I tried this, but I can't see any log message yet.

Thanks!

**Comment by ChadKillingsworth** [comment]
I don't use sentry with supervisord, so I'm not sure how to help with this. What you have tried worked for me.

**Comment by jirutka** [comment]
@tiago-cruz-movile Try to add the following snippet to `sentry.conf.py`:

``` py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG'
        }
    }
}

import logging
logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
logger.setLevel('DEBUG')
```

**Comment by felixbuenemann** [comment]
I had the same problem and it worked after adding the `LOGGING` entry mentioned above by @jirutka.

**Comment by DenisBY** [comment]
I've tried solution above, but now I'm getting:

```
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 9, in <module>
    load_entry_point('sentry==8.7.0', 'console_scripts', 'sentry')()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 159, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 65, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 122, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 219, in initialize_app
    configure_structlog()
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 198, in configure_structlog
    settings.LOGGING['root'].update({
KeyError: 'root'
```

**Comment by dirkdevriendt** [comment]
Same here. Ironically, the logging setup in sentry is a bit obscure, but basically the problem is that LOGGING exists already, so I had success with the following lines in `sentry.conf.py`:

```
LOGGING['overridable'] = ['sentry', 'django_auth_ldap']
LOGGING['loggers']['django_auth_ldap'] = {
        'handlers': ['console']
}
```

... and then starting the web server with '--loglevel DEBUG'

references:
- https://docs.sentry.io/server/cli/run/web/
- https://github.com/getsentry/sentry/blob/827043e3a44cfb5e79e1db033ec93c28ac37ea3c/src/sentry/conf/server.py
