### ISSUE TITLE
getsentry-ldap-auth seems not work with sentry docker install

### ISSUE THREAD

**Issue by HackToday** [Banno/getsentry-ldap-auth#28]
Env:  CentOS 7.2 

How to reproduce:

1. git clone https://github.com/getsentry/onpremise
2. change Dockerfile like this 

```
FROM sentry:8.21-onbuild

RUN pip install git+https://github.com/Banno/getsentry-ldap-auth.git
```

3.  Hit error like this

```
Sending build context to Docker daemon 18.43 kB
Step 1 : FROM sentry:8.21-onbuild
# Executing 4 build triggers...
Step 1 : COPY . /usr/src/sentry
 ---> Using cache
Step 1 : RUN if [ -s requirements.txt ]; then pip install -r requirements.txt; fi
 ---> Running in 0476a02d5428
Collecting django-auth-ldap (from -r requirements.txt (line 2))
  Downloading django_auth_ldap-1.3.0-py2.py3-none-any.whl
Collecting django>=1.8 (from django-auth-ldap->-r requirements.txt (line 2))
  Downloading Django-2.0.tar.gz (8.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-OyDT77/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'

```

**Comment by barronhagerman** [comment]
This should be fixed now with v2.5
